# Generated by Django 5.1 on 2024-08-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facadlib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesToMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
